version: "3"

networks:
  app-frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.1.0/24
  app-backend:
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 172.10.2.0/23

services:
  app-db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    networks:
      app-backend:
        ipv4_address: 172.10.3.2
    env_file:
      - ./dev.env
  app-www:
    build: ./www
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html/
    networks:
      app-backend:
        ipv4_address: 172.10.2.2
      app-frontend:
        ipv4_address: 172.10.1.2
    depends_on:
      - app-db
    env_file:
      - ./dev.env
